/**
 * Mock Anthropic responses used when ANTHROPIC_API_KEY is not set.
 * Provides realistic-looking output for development and testing.
 */

import { AgentType, AgentOutput, FileChange } from '../types/index.js';

/**
 * Generates a pair of mock source and test files for a given task.
 * File paths are derived from the task string (lowercased, hyphenated).
 */
function makeMockFiles(task: string, repo: string): FileChange[] {
  const safeTask = task.replace(/\s+/g, '-').toLowerCase().slice(0, 30);
  return [
    {
      path: `src/${safeTask}.ts`,
      content: `// Generated by DevFoundry FeatureAgent\n// Task: ${task}\n// Repo: ${repo}\n\nexport function generatedFeature() {\n  // Implementation generated by AI\n  return true;\n}\n`,
      operation: 'create',
    },
    {
      path: `src/${safeTask}.test.ts`,
      content: `import { generatedFeature } from './${safeTask}';\n\ndescribe('generatedFeature', () => {\n  it('should work correctly', () => {\n    expect(generatedFeature()).toBe(true);\n  });\n});\n`,
      operation: 'create',
    },
  ];
}

/** Generates a unified diff string from a list of file changes. */
function makeDiff(files: FileChange[]): string {
  return files
    .map(
      (f) =>
        `--- /dev/null\n+++ b/${f.path}\n@@ -0,0 +1,${f.content.split('\n').length} @@\n${f.content
          .split('\n')
          .map((l) => `+${l}`)
          .join('\n')}`,
    )
    .join('\n\n');
}

/**
 * Builds a complete mock {@link AgentOutput} for a given agent type and task.
 *
 * Used by {@link BaseAgent} when `ANTHROPIC_API_KEY` is not set and `allowMock`
 * is `true`. All mock outputs include a `[MOCK]` note so they are easy to
 * identify in logs and test output.
 *
 * @param agentType - The agent type determining the summary template.
 * @param task - The task description passed to the agent.
 * @param repo - The target repository name.
 */
export function buildMockOutput(
  agentType: AgentType,
  task: string,
  repo: string,
): AgentOutput {
  const files = makeMockFiles(task, repo);
  const diff = makeDiff(files);

  const summaries: Record<AgentType, string> = {
    feature: `Implemented feature: "${task}" with ${files.length} file(s) changed.`,
    test: `Generated test suite for: "${task}" covering happy path and edge cases.`,
    refactor: `Refactored code in ${repo} for: "${task}" improving readability and reducing complexity.`,
    security: `Security analysis complete for ${repo}. Scanned for OWASP Top 10 vulnerabilities.`,
    dependency: `Dependency update complete for ${repo}. Bumped packages to latest compatible versions.`,
    'pr-reviewer': `PR review complete. Found 0 critical issues. Approved with minor suggestions.`,
  };

  return {
    agentType,
    task,
    repo,
    summary: summaries[agentType] ?? `Completed task: ${task}`,
    files,
    diff,
    paths: files.map((f) => f.path),
    tests: [files[1]?.path ?? ''],
    notes: ['[MOCK] This is a simulated response — set ANTHROPIC_API_KEY for real AI output.'],
    rawResponse: '[mock response]',
    usage: { inputTokens: 0, outputTokens: 0 },
  };
}
