global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'products-service'
    static_configs:
      - targets: ['products-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s