apiVersion: v1
kind: Secret
metadata:
  name: onya-secrets
  namespace: onya-chatbot
type: Opaque
data:
  # Base64 encoded secrets - these would be managed by external secrets operator
  # or injected during deployment
  database-url: cG9zdGdyZXNxbDovL29ueWFfc3RhZ2luZzpwYXNzd29yZEBzdGFnaW5nLXBvc3RncmVzOjU0MzIvb255YV9zdGFnaW5n
  redis-url: cmVkaXM6Ly9zdGFnaW5nLXJlZGlzOjYzNzk=
  jwt-secret: c3RhZ2luZy1qd3Qtc2VjcmV0LWtleQ==
  jwt-refresh-secret: c3RhZ2luZy1qd3QtcmVmcmVzaC1zZWNyZXQta2V5
  service-token: c3RhZ2luZy1zZXJ2aWNlLXRva2Vu
  openai-api-key: c2stZmFrZS1vcGVuYWkta2V5LWZvci1zdGFnaW5n
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onya-config
  namespace: onya-chatbot
data:
  NODE_ENV: "staging"
  LOG_LEVEL: "debug"
  LLM_PROVIDER: "mock"
  CORS_ORIGIN: "https://staging.onya.com"
  METRICS_ENABLED: "true"
  TRACE_SAMPLING_RATE: "1.0"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: onya-chatbot
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onya-external-secrets
  namespace: onya-chatbot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: onya-secrets-external
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: onya/staging/database
      property: url
  - secretKey: redis-url
    remoteRef:
      key: onya/staging/redis
      property: url
  - secretKey: jwt-secret
    remoteRef:
      key: onya/staging/jwt
      property: secret
  - secretKey: jwt-refresh-secret
    remoteRef:
      key: onya/staging/jwt
      property: refresh-secret
  - secretKey: openai-api-key
    remoteRef:
      key: onya/staging/openai
      property: api-key